name: release-flow

on:
  push:
    branches: [main]

jobs:
  tag_and_next_dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # нужны теги и вся история
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install uv & deps
        run: pip install uv packaging
      - name: Stage 5 – tag
        run: uv pip run python -m release_tool.stage5 --push
      - name: Stage 6 – next-dev
        run: uv pip run python -m release_tool.stage6 --branch dev_branch --push